[tool.poetry]
name = "bundler"
version = "0.1.0"
description = ""
authors = ["JulesBelveze <jules.belveze@hotmail.fr>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.1"
bokeh = "^2.4.3"
pandas = "^1.4.3"
python-dotenv = "^0.20.0"
requests = "^2.28.1"
pillow = "^10.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
